Added support to read-out the SI sensor revision and model
adafruit/Adafruit_Si7021 pull request #4
Opened 2018-03-17 14:04 UTC by helmut64

Added support to read-out the SI sensor revision and model
Optimized measurement duration delays for faster reads to save energy.

2018-07-30 18:20 UTC, helmut64 commented
Please merge this changes because it includes important changes for the ESP32 to work with the latest ESP32 Arduino versions, It includes further cleanups as well.

2018-07-30 18:22 UTC, ladyada commented
hi please move #defines back into the .h file

2018-07-30 18:53 UTC, helmut64 commented
Hi ladyada , this local defines should be used only within the implementation therefore they don't belong the the .h public file. At least this is my understanding of C++. If you wish I can convert the #defines into a private enum within the class, this would be even better.
However if you insist on putting it back I can do so.
Regards Helmut

2018-07-30 21:12 UTC, ladyada commented
yep thanks

2018-08-03 18:52 UTC, helmut64 commented
Any news on the merge.

2018-08-03 18:54 UTC, ladyada commented
nope. might be a bit till we get to it, thanks!

2018-08-26 12:14 UTC, Rotzbua requested changes

2018-08-26 12:14 UTC, Rotzbua commented on Adafruit_Si7021.cpp
> +	  if (Wire.requestFrom(_i2caddr, 3) == 3) {
Same code style would be good.
Replace tab by space for equal code style :+1:

2018-08-26 12:14 UTC, Rotzbua commented on Adafruit_Si7021.cpp
> +		uint32_t start = millis(); // start timeout
spaces instead of tab

2018-08-26 12:14 UTC, Rotzbua commented on Adafruit_Si7021.cpp
> +            _model = "SI engineering samples";
chars are ugly, prefer `enum`
chars are more difficult to handle in a program
chars are present in RAM which are a real thread on AVR arduinos
this lines of code will eat about `65 byte` of RAM!

2018-08-26 12:14 UTC, Rotzbua commented on Adafruit_Si7021.h
> +  const char *_model;
prefer a `enum` over `char`

2018-08-26 12:14 UTC, Rotzbua commented on Adafruit_Si7021.cpp
> +  		uint8_t chxsum = Wire.read();
space instead of tab
add a comment that chxsum is not used and could be a `todo: implement checksum`

2018-08-26 12:14 UTC, Rotzbua commented on Adafruit_Si7021.cpp
> +  _model = "Si7021";
`   uint8_t _revision; `
is not initialized

2018-08-27 09:40 UTC, helmut64 commented
The tabs are now spaces, sorry I was using a different editor.
Optimized the model handling to use enums. Strings are being linked into it only if a user calls getModel() which is a good tradeoff to save Flash memory.

2018-08-27 10:46 UTC, Rotzbua commented
Thanks for the quick response :+1:

2018-08-27 10:46 UTC, Rotzbua commented on Adafruit_Si7021.h
> +  const char *getModel(void);
I would prefer:
```c++
sensorType getModel(void);
```

And for print/debug a function with string as return, maybe named:
```c++
const char *getModelDebug(void); 
const char *getModelString(void); 
const char *getModelPrintable(void);

2018-08-27 13:43 UTC, helmut64 commented
Hi Rotzbua, thanks for the feedback, I enhanced it further, which makes sense.

BTW: Do habe you merge rights on the ArduinoCore-samd, I did some changes for our board and it takes them always 9 month to respond. https://github.com/arduino/ArduinoCore-samd/pull/331

Regards Helmut

2018-08-27 15:59 UTC, ladyada commented
hiya - nice updates! can you remove this 
https://github.com/adafruit/Adafruit_Si7021/pull/4/files#diff-59ef3228d3e21cc6ad675e5e7b0b3515R221
and put it in the example sketch instead? that is, a function that will decode the # and print the string

2018-08-28 08:40 UTC, helmut64 commented
Hi Limor, I don't understand.
Should I put in the SI version printout via getModelName() as well into the example sketch, no problem.
The getModelName() function belongs to the library and does not costs any space unless it is being used by an program. The linker skips unused functions.
Please advise. Regards Helmut
PS: I sent to you some information regarding our ECO Power ESP32 Boards, I hope you received it.

2018-08-28 20:12 UTC, ladyada commented
yah i dont like having functions that return strings in libraries - maybe its just me :) i'd prefer it returns an ENUM and then the script decodes that, if that's ok by you! :)

2018-08-29 07:39 UTC, helmut64 commented
Actually for users this is very convenient, see my printf example here:

`printf("%s: Rev(%d)  %.2f°C  Humidity: %.2f%%", sensorSI7021->getModelName(), sensorSI7021->getRevision(), sensorSI7021->readTemperature(), sensorSI7021->readHumidity());
`
Also it does not cost anything because strings use no Flash memory when getModelName is not being used. Another point is that the lC++ library is a block of ready to use code which provides everything needed for the device.

It would be great if you can merge this, I will add the model info into the example code.
PS: I am happy to help to enhance it further in the future upon needs.

2018-09-14 16:16 UTC, merged

2018-09-14 16:17 UTC, ladyada commented
ok i made some changes and merged! @ChuckVanzant can you try the latest commit to master? If y'all are OK with it, i'll make a new arduino library release

2018-09-14 18:27 UTC, ChuckVanzant commented
The latest merge from helmut64 seems to break SI7021 working on ESP32.

If I comment out the following 

#ifdef ARDUINO_ARCH_ESP32
if (err != I2C_ERROR_CONTINUE) //ESP32 has to queue ReSTART operations.
#else
if(err != 0)
#endif
return NAN; //error

in the following methods, it seems to work on ESP32:
       Adafruit_Si7021::readTemperature(void)
       Adafruit_Si7021::readHumidity(void)

2018-09-14 20:28 UTC, helmut64 commented
@ChuckVanzant removing the "if (err != I2C_ERROR_CONTINUE)" it wrong.
The ESP32 has one I"C error code which must be accepted and the while loop will take care about the async CONTINUE situation..
Where was the problem with the I2C_ERROR_CONTINUE?
Maybe it was not available in your ESP32 SDK because it is older not not included in the header files, in this case a "I2C_ERROR_CONTINUE can be replaced by "7".

PS: I spend all the time to bring the driver up to speed, and your commit changes without giving me a chance to review it.

Regards Helmut

2018-09-14 20:31 UTC, ladyada commented
hiya, please keep it positive so we can work together to solve the ESP32 complexity - all PR's are reviewed and tested by the adafruit team on Arduino boards! sometime we make mistakes - we have many PR's and issues every day - but we will get it working

2018-09-14 20:33 UTC, helmut64 commented
No problem, we get this done together.
Regards from the Hannover Maker Faire at Arduino-Hannover booth.

2018-09-14 20:35 UTC, ChuckVanzant commented
Then simply restore the "false" argument to the calls to Wire.endTransmission() and all should be good.

2018-09-14 20:49 UTC, helmut64 commented
@ChuckVanzant I will get into the details Monday, this weekend I am busy at the Maker Faire.
Regards Helmut